name: Build and test
on:
  push:
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  desktop:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-14, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.3'
          modules: 'qtmultimedia'
          cache: true
      - uses: ilammy/msvc-dev-cmd@v1
        if: runner.os == 'Windows'
      - name: Configure
        run: cmake --preset debug
      - name: Build
        run: cmake --build --preset debug --parallel 4
      - name: Test
        run: ctest --preset debug
      - name: Deploy
        run: cmake --install build/debug --prefix build/package
      - uses: actions/upload-artifact@v4
        with:
          name: qDing-${{ runner.os }}
          path: build/package/

